# Druid连接池
druid:
  username: admin
  password: admin
# MySQL数据库
mysql:
  domain: wyatt.run:9001
  username: db_access
  password: PZvVdnpwJLS83yu/1A3bcEpCvDNErNWWfSuu0a1AUnps6UaR0o6ozvjYQJltl+uyjYVR0mw0QZFsole3KtaS4Q==
  public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOPSlUVOw2Wq+mX+KGcyd98jWOnK223S+69leJyfIiRHuxm55fQcvqlFfxc65DRUOsL20OsBH16zjxvHJXJSXzsCAwEAAQ==
logging:
  # 级别依次为（从高到低）：FATAL > ERROR > WARN > INFO > DEBUG > TRACE
  level:
    root: info
    # 为包设置特定日志级别，可以覆盖上层设定的日志级别
    org.springframework: info
    org.apache: info
    org.mybatis: info
    run.wyatt.oneplatform: info
    run.wyatt.oneplatform.dao: debug # 设为debug可以查看SQL
