sys:
  # 系统运行环境：
  #   1.开发测试环境：dev
  #   2.本地运行（测试）：local  此环境应用配置与生产一致，不过连接的数据库和缓存是远程服务器开发测试环境的实例
  #   3.服务器运行（生产）：run
  env: dev

server:
  port: 8002
spring:
  profiles:
    active: ${sys.env}
  application:
    name: oneplatform-system
  boot:
    # 服务监控
    admin:
      client:
        url: http://${sys.op-monitor.domain}
  cloud:
    # 服务注册
    consul:
      host: ${sys.op-registry.host}
      port: ${sys.op-registry.port}
      discovery:
        serviceName: ${spring.application.name}
  redis:
    database: 0
    host: ${sys.redis.host}
    port: ${sys.redis.port}
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
# 为服务监控中心开放健康检查接口，即对/actuator/*路径的访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
