server:
  port: 8001

spring:
  application:
    name: oneplatform-monitor
  profiles:
    active: run

# 为服务监控中心开放健康检查接口，即对/actuator/*路径的访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
