sys:
  # 系统运行环境：
  #   1.开发测试环境：dev
  #   2.服务器运行（生产）：run
  env: run

server:
  port: 8000
spring:
  cloud:
    # 服务网关
    gateway:
      routes:
        - id: OnePlatformSystem
          uri: http://${sys.op-system.domain}
          predicates:
            - Path=/api/sys/**
        - id: OnePlatformFinance
          uri: http://${sys.op-finance.domain}
          predicates:
            - Path=/api/finance/**
        - id: OnePlatformTodo
          uri: http://${sys.op-todo.domain}
          predicates:
            - Path=/api/todo/**
    # 服务注册
    consul:
      host: ${sys.op-registry.host}
      port: ${sys.op-registry.port}
      discovery:
        serviceName: ${spring.application.name}
  profiles:
    active: ${sys.env}
  application:
    name: oneplatform-gateway
  boot:
    # 服务监控
    admin:
      client:
        url: http://${sys.op-monitor.domain}
# 为服务监控中心开放健康检查接口，即对/actuator/*路径的访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
