sys:
  op-registry:
    host: localhost
    port: 8500
    domain: ${sys.op-registry.host}:${sys.op-registry.port}
  op-monitor:
    host: localhost
    port: 8001
    domain: ${sys.op-monitor.host}:${sys.op-monitor.port}
  op-system:
    host: localhost
    port: 8002
    domain: ${sys.op-system.host}:${sys.op-system.port}
  op-finance:
    host: localhost
    port: 8003
    domain: ${sys.op-finance.host}:${sys.op-finance.port}