sys:
  # 系统运行环境：
  #   1.开发测试环境：dev
  #   2.本地运行（测试）：local  此环境应用配置与生产一致，不过连接的数据库和缓存是远程服务器开发测试环境的实例
  #   3.服务器运行（生产）：run
  env: dev

server:
  port: 8000
spring:
  profiles:
    active: ${sys.env}
  application:
    name: oneplatform-gateway
  boot:
    # 服务监控
    admin:
      client:
        url: http://${sys.op-monitor.domain}
  cloud:
    # 服务注册
    consul:
      host: ${sys.op-registry.host}
      port: ${sys.op-registry.port}
      discovery:
        serviceName: ${spring.application.name}
    # 服务网关
    gateway:
      routes:
        - id: getKaptcha
          uri: http://${sys.op-system.domain}
          predicates:
            - Path=/api/getKaptcha
        - id: login
          uri: http://${sys.op-system.domain}
          predicates:
            - Path=/api/login
        - id: getProfile
          uri: http://${sys.op-system.domain}
          predicates:
            - Path=/api/getProfile
        - id: logout
          uri: http://${sys.op-system.domain}
          predicates:
            - Path=/api/logout
# 为服务监控中心开放健康检查接口，即对/actuator/*路径的访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
