sys:
  op-registry:
    host: oneplatform-registry
    port: 8500
    domain: ${sys.op-registry.host}:${sys.op-registry.port}
  op-monitor:
    host: oneplatform-monitor
    port: 8001
    domain: ${sys.op-monitor.host}:${sys.op-monitor.port}
  op-system:
    host: oneplatform-system
    port: 8002
    domain: ${sys.op-system.host}:${sys.op-system.port}
  op-finance:
    host: oneplatform-finance
    port: 8003
    domain: ${sys.op-finance.host}:${sys.op-finance.port}
  op-todo:
    host: oneplatform-todo
    port: 8004
    domain: ${sys.op-todo.host}:${sys.op-todo.port}