spring:
  boot:
    # 服务监控
    admin:
      client:
        url: "http://basic-monitor:8001"
  cloud:
    # 服务注册
    consul:
      host: basic-registry
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
