spring:
  application:
    name: basic-monitor
  profiles:
    active: run

server:
  port: 8001

# 为服务监控中心开放健康检查接口，即对/actuator/*路径的访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
