server:
  port: 8002
spring:
  profiles:
    active: dev # 开发环境：run，测试环境：dev，本地运行：localrun（连的测试数据库）
  application:
    name: oneplatform-user
  boot:
    # 服务监控
    admin:
      client:
        url: "http://localhost:8001"
  # druid数据源
  datasource:
    # 数据库连接参数
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/db_oneplatform?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: ${db.username}
    password: ${db.password}
    # Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    filters: config,stat,wall,log4j
    connection-properties: config.decrypt=true;config.decrypt.key=${db.public-key}
    max-active: 100
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 50
    max-pool-prepared-statement-per-connection-size: 20
# 为服务监控中心开放健康检查接口，即对/actuator/*路径的访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
