server:
  port: 8002
spring:
  profiles:
    active: dev # 开发环境：run，测试环境：dev，本地运行：localrun（连的测试数据库）
  application:
    name: oneplatform-user
  boot:
    # 服务监控
    admin:
      client:
        url: "http://localhost:8001"
  datasource:
    host: ${db.host}
    port: ${db.port}
    username: ${db.username}
    password: ${db.password}
    public-key: ${db.public-key}
  redis:
    database: 0
    host: ${redis.host}
    port: ${redis.port}
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
# 为服务监控中心开放健康检查接口，即对/actuator/*路径的访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
