spring:
  boot:
    # 服务监控
    admin:
      client:
        url: "http://localhost:8001"
  cloud:
    # 服务注册
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
sys:
  db:
    host: wyatt.run
    port: 9000
