spring:
  boot:
    # 服务监控
    admin:
      client:
        url: "http://oneplatform-monitor:8001"
  cloud:
    # 服务注册
    consul:
      host: oneplatform-registry
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
db:
  host: oneplatform-mysql
  port: 9000
  username: db_access
  password: unkown
  public-key: unkown
redis:
  host: oneplatform-redis
  port: 9100