sys:
  mysql:
    domain: oneplatform-mysql:3306
    username: db_access
    password: 部署前填写
    public-key: 部署前填写
  redis:
    host: oneplatform-redis
    port: 6379
  op-registry:
    host: oneplatform-registry
    port: 8500
    domain: ${sys.op-registry.host}:${sys.op-registry.port}
  op-monitor:
    host: oneplatform-monitor
    port: 8001
    domain: ${sys.op-monitor.host}:${sys.op-monitor.port}